language: node_js

node_js: stable

install:
  - npm install
  
cache:
  npm: false
  
script:
  - hexo clean
  - hexo generate
  - npm run build

after_script:
  - cd ./public
  - git init
  - git config user.name "xiaolong"
  - git config user.email "refactoring@aliyun.com"
  - git add .
  - git commit -m "publish some articles"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - gh-pages
env:
 global:
   - GH_REF: github.com/xiaolony/xiaolony.github.io.git
